site_name: CHIFEngine
site_url: https://lukasrennhofer.github.io/CHIFEngine

theme:
  name: 'dracula'
  features:
    - navigation.tabs      # Enable tab navigation for better content organization
    - search.suggest       # Enable search suggestions while typing
    - header.autohide      # Autohide the header when scrolling down
    - footer.links         # Show footer links for additional resources

# Plugins to enhance functionality
plugins:
  - search                # Search functionality for easy content navigation
  - git-revision-date-localized  # Shows last commit date on each page
  - markdownextradata     # Extracts additional metadata for Markdown (optional)

# Pages and Navigation
nav:
  - Home: index.md
  - API Documentation:
      - CHIFEngineAPI: CHIFEngineAPI/CHIFEngineAPI.md
  - Future Plans: FuturePlans.md
  - Contributing: CONTRIBUTING.md
  - Architecture: Project/ARCHITECTURE.md

# Code highlighting and extensions
markdown_extensions:
  - codehilite:
      guess_lang: false  # Better language detection for code blocks
  - pymdownx.snippets  # Allows the use of code snippets in Markdown
  - toc:
      permalink: true    # Enable permanent links in the table of contents

# Define the theme configuration for better user experience
extra:
  social:
    - icon: fontawesome/brands/github
      link: 'https://github.com/LukasRennhofer/CHIFEngine'
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/LRDevOfficial'

